name: Publish NPM Private Registry
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install gRPC tools
        run: npm install -g grpc-tools

      - name: Install npm
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Set PATH for node_modules/.bin
        run: export PATH=$PATH:./node_modules/.bin

      - name: check node_modules path
        run: ls -la ./node_modules/.bin

      - name: Generate Protobuf
        run: make generate-protobuf
        working-directory: .

      - name: Set NPM_TOKEN and .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@nagamoridaiki:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Private NPM Registry
        run: |
          npm publish ./generated/ --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
