name: Publish NPM Private Registry
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set NPM_TOKEN and .npmrc
        run: |
          echo "npm.pkg.github.com/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          echo "@nagamoridaiki:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Debug .npmrc
        run: cat ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Publish to Private NPM Registry
        run: |
          npm publish --registry=https://npm.pkg.github.com
